package Gun35._01_Final.Method;

public class Ucak {


    //FİNAL DEĞİŞKENLERİN BAŞINDA OLDUĞUNDA DEĞERİ SONRADAN DEĞİŞTİRİLEMEZ
    //METODLARIN BAŞINDA OLDUĞUNDA OVERRİDE EDİLEMEZLER
    //CLASLARIN BAŞINDA OLDUĞUNDA İSE EXTEND EDİLEMEZLER

}
